### ISSUE TITLE
sending strings with send_sysex

### ISSUE THREAD

**Issue by sunfffd** [tino/pyFirmata#14]
First of all thank you for the library, it's great :+1:  :)

I'm trying to send some strings from my python script to my arduino using send_sysex, so the string got displayed on a LCD screen (GLCD lib)

in my .py script, I'm trying

```
board.send_sysex(0x71, ["test message"])
```

0x71 being STRING_DATA message

and on my arduino

``` perl
void lcdDisplayString(char *msg){
  GLCD.CursorTo(0,1);
  GLCD.print(msg);
}

void setup(){
/*
some init code here
*/
Firmata.setFirmwareVersion(0,1);
Firmata.attach(STRING_DATA, lcdDisplayString);
Firmata.begin(57600);
}
```

However, I'm getting some malformed characters from the display.
I'm wondering if the send_sysex() function from pyFirmata and the Firmata.processInput() in Arduino are sending and accepting the whole string or characters one by one.

**Comment by tino** [comment]
Is this still a problem now that we are using byte arrays?

**Comment by tino** [comment]
Closing, as I can't move forward with this. Hopefully it's not a problem anymore!
