### ISSUE TITLE
Timing issue with analog reads

### ISSUE THREAD

**Issue by brammeleman** [tino/pyFirmata#16]
Hi,

I could not manage to setup a reliable connection between my pc and arduino (standard firmata sketch). The confusing part is that it all seems to work in the python command line, but when running the example code in a small script, analog reads return 'None'. After inserting a little pause (emulating manual execution in the python shell), analog read does output some values.

Here's my test-script:

``` python
#!/usr/bin/env python
import time
from pyfirmata import Arduino, util
board = Arduino('/dev/ttyUSB0')
it = util.Iterator(board)
it.start()
board.analog[0].enable_reporting()
print board.analog[0].read()
print board.analog[0].read()
print board.analog[0].read()
print board.analog[0].read()
time.sleep(1)
print board.analog[0].read()
print board.analog[0].read()
print board.analog[0].read()
print board.analog[0].read()
board.exit()
```

...and it's output:

```
None
None
None
None
0.6354
0.6354
0.6354
0.6354
```

As mentioned, when just typing the statements in the python shell it just seems to work fine:

```
>>> import time
>>> from pyfirmata import Arduino, util
>>> board = Arduino('/dev/ttyUSB0')
>>> it = util.Iterator(board)
>>> it.start()
>>> board.analog[0].enable_reporting()
>>> print board.analog[0].read()
0.6129
>>> print board.analog[0].read()
0.567
>>> print board.analog[0].read()
0.5787
>>> print board.analog[0].read()
0.607
.... etc
```

Used hard-/software:
pyFirmata 0.95 in python 2.7.3
Firmata 2.3.5 on an Arduino duemilanova (ATmega328 version)

Any clue?

Bests,

Bram

**Comment by tino** [comment]
Closing, as I can't move forward with this. Hopefully it's not a problem anymore!
