### ISSUE TITLE
Version bump (0.9.6) and deploy

### ISSUE THREAD

**Issue by theycallmeswift** [tino/pyFirmata#26]
Looks like there have been a number of changes since 0.9.5.  We need to bump and deploy.  I don't have access to pypi so you'll have to do it.  

LMK if you have any issues with this.  If not, I'll tag and bump and you can push.

**Comment by aginiewicz** [comment]
I'd really like to see a release of this library - especially one with support for Python 3. Will py3 be merged before 0.9.6 and accessible trough PyPi? This is last library that stops me from moving to python 3 only toolchain - and moving whole textbook and lab for class I teach to Python 3.

**Comment by tino** [comment]
You've got it. Version 1.0.0 is out!

**Comment by aginiewicz** [comment]
Thanks! I will check it out tomorrow, keep up great work!
