### ISSUE TITLE
Setting analog pins to output

### ISSUE THREAD

**Issue by antonbilbaeno** [tino/pyFirmata#31]
Is it possible to set A0-A5 to outputs?
I seem to be able to set the pin mode to OUTPUT (no errors when running my Python script), but am unable to measure 5V on the pin itself.

import pyfirmata
PORT = '/dev/ttyACM0'
board = pyfirmata.Arduino(PORT)
board.analog[0].mode = pyfirmata.OUTPUT
board.analog[0].write(1) #have also tried .write(255)

I will see A0 go to ~0.1 V or ~0.3 V. I measure similar voltages across all of the analog pins once I set board.analog[0].mode = pyfirmata.OUTPUT.

**Comment by tino** [comment]
I guess it's possible, see firmata/arduino#139. I don't have the time to implement that though. Closing for now.

**Comment by whc2001** [comment]
Is there a solution now? I am running into the same issue.
