### ISSUE TITLE
Nano on pypi

### ISSUE THREAD

**Issue by narius** [tino/pyFirmata#80]
Hi
Thanks for a great package :). In the code here on github you have ArdunioNano in boards and __init__.py. But when you run pip install pyfirmata you doesn't get ArduinoNano. Would it be possible to publish new code to pypi.org?

**Comment by tino** [comment]
Hi, I just pushed 1.1, which includes those change.

Well overdue, thanks for the reminder!

**Comment by narius** [comment]
Thanks :)
