### ISSUE TITLE
Re-assign pin usage

### ISSUE THREAD

**Issue by cymplecy** [tino/pyFirmata#9]
Thanks for lovely library :)
I'm using your code for a Scratch-Arduino interface. 
http://cymplecy.wordpress.com/2013/01/12/scratch-controlling-shrimparduino/
 I want to assume pins6-13 are digital outputs but if I receive a motor11 xx message then I'd like to re-assign pin11 to be a pwm output.  Is this possible with the current code or will I have to decide to dedicate some pwm outputs at the start of my code?

**Comment by evgeshakrasava** [comment]
guys hi! 
i think my question some weird but i wanna know how .
how change speed for servo.
in my happening , have 9 servo with another function .big problem in this stuff it is speed.sorry by my english
